import type { JsonRecord } from "./types.js";
export declare const ACTION_PROTOCOL_VERSION = "noderooms-action-idempotency-v1";
export declare const ACTION_ID_PATTERN: RegExp;
export declare const RECEIPT_ID_PATTERN: RegExp;
export declare const FINGERPRINT_PATTERN: RegExp;
export declare const ACTION_STATUSES: readonly string[];
export declare const IDEMPOTENCY_STATUSES: readonly string[];
export type ActionType = "guest_post" | "guest_comment";
export type ActionStatus = "committed" | "failed" | "processing" | "unknown";
export type IdempotencyStatus = "created" | "replayed";
export type ActionIdentity = {
  actionId: string;
  fingerprintSha256: string;
};
export type CanonicalReceipt = JsonRecord & {
  ok: boolean;
  protocol_version: "noderooms-action-idempotency-v1";
  action_id: string;
  receipt_id: string;
  action_type: ActionType;
  action_status: ActionStatus;
  idempotency_status: IdempotencyStatus;
  fingerprint_sha256: string;
  server_idempotency_enforced: true;
  duplicate_write_prevented: true;
  unknown_outcome_replay_blocked: true;
  replay_blocked: boolean;
  public_write_attempted: boolean;
  dispatch_count: number;
  exactly_once_effect: false;
  object_id: number | null;
  public_url: string | null;
  error_code: string | null;
  error_message: string | null;
};
export declare function assertActionIdentity(actionId: string, fingerprintSha256: string): ActionIdentity;
export declare function actionHeaders(actionId: string, fingerprintSha256: string, existing?: Record<string,string>): Record<string,string>;
export declare function validateActionProtocolStatus(value: JsonRecord): JsonRecord;
export declare function validateCanonicalReceipt(value: JsonRecord, expected?: Partial<{actionId:string; fingerprintSha256:string; actionType:ActionType}>): CanonicalReceipt;
export declare function actionOutcomeFromReceipt(receipt: JsonRecord): JsonRecord;
